sudo: required
addons:
  chrome: stable

language: ruby
rvm:
  - 2.5.1
services: mongodb
env:
  - DATABASE_USERNAME=travis
before_install:
  - gem install bundler
  - yarn install
before_script:
  - bundle exec rake db:create db:migrate
notifications:
  - false
script:
  - bundle exec rubocop
  - bundle exec rspec

