version: '3'

services:
  postgres_db:
    image: 'postgres:10-alpine'
    environment:
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    depends_on:
      - postgres_db
    build: .
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/lunch_app
    ports:
      - '3000:3000'
    env_file:
      - '.env'

volumes:
  postgres:
